ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*

USER_LIB_PATH = ${HOME}/Sketchbook/libraries

ARDUINO_LIBS = ros_lib SimpleDHT HX711

BOARD_TAG = mega2560
include /usr/share/arduino/Arduino.mk
