ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*
ARDUINO_SKETCHBOOK = ${HOME}/Sketchbook

ARDUINO_LIBS = ros_lib DHT20 HX711 Wire

BOARD_TAG = mega2560
include /usr/share/arduino/Arduino.mk
