ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*

#USER_LIB_PATH = /home/osboxes/arduino-1.8.9/libraries
USER_LIB_PATH = /home/robotanist/Sketchbook/libraries

ARDUINO_LIBS = ros_lib SimpleDHT

BOARD_TAG = mega2560
include /usr/share/arduino/Arduino.mk
