#!/bin/bash

source mediamtx-ctl
start_mediamtx
trap cleanup EXIT

WIDTH=1280
HEIGHT=720
RATE=30
CARD=$(arecord -l | awk -F: '/Elf/ {print $1}' | awk '{print $2}' | head -n1)

echo "Starting video + audio stream..."
rpicam-vid --width $WIDTH --height $HEIGHT --framerate $RATE\
   -t 0 -v 0 -o - --codec h264 --inline --profile baseline --bitrate 2000000 |\
   ffmpeg -fflags nobuffer -flags low_delay -flush_packets 1 \
      -analyzeduration 1000000 -probesize 1000000 \
      -loglevel warning \
      -thread_queue_size 512 -f h264 -i - \
      -thread_queue_size 512 -f alsa -ac 2 -i hw:$CARD,0 \
      -c:v copy -c:a aac -b:a 96k \
      -f rtsp rtsp://localhost:8554/stream
